# Generated by Django 5.2.8 on 2025-11-27 07:41

import analytics.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="e.g., 'Midterm Exams - Class 8 West - 2024'", max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Unique URL identifier, auto-generated from title.', max_length=255, unique=True)),
                ('file', models.FileField(help_text='Upload your exam data file here (Excel or CSV only)', upload_to=analytics.models.exam_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv'])])),
                ('grading_scheme', models.JSONField(default=analytics.models.default_grading_scheme, help_text='Custom grading rules (JSON) for this specific exam.')),
                ('custom_ignore_columns', models.CharField(blank=True, help_text="Comma-separated list of columns to exclude from grading (e.g., 'UPI, Nemis No, Stream').", max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Processing notes or error messages.', null=True)),
                ('analysis_summary', models.JSONField(blank=True, default=dict, help_text='JSON summary of results (avg, pass_rate, etc.)')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('subject_chart', models.ImageField(blank=True, null=True, upload_to='charts/%Y/%m/')),
                ('passrate_chart', models.ImageField(blank=True, null=True, upload_to='charts/%Y/%m/')),
                ('reports_zip', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam File Upload',
                'verbose_name_plural': 'Exam File Uploads',
                'ordering': ['-uploaded_at'],
                'permissions': [('can_process_exam', 'Can trigger exam processing')],
            },
        ),
    ]
