# Generated by Django 5.2.8 on 2025-11-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Midterm Exams - Class 8 west - 2024'", max_length=255)),
                ('file', models.FileField(help_text='Upload your exam data file here (Excel, CSV, etc.)', upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Processing notes or error messages will appear here.', null=True)),
            ],
        ),
    ]
