# Generated by Django 5.2.8 on 2025-11-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Exam File Upload', 'verbose_name_plural': 'Exam File Uploads'},
        ),
    ]
