# Generated by Django 5.2.8 on 2025-11-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examupload',
            name='passrate_chart',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
        migrations.AddField(
            model_name='examupload',
            name='subject_chart',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
    ]
