# Generated by Django 5.2.8 on 2025-11-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_examupload_passrate_chart_examupload_subject_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='examupload',
            name='reports_zip',
            field=models.FileField(blank=True, help_text='A ZIP file containing individual student reports.', null=True, upload_to='reports/%Y/%m/%d/'),
        ),
    ]
