# Generated by Django 5.2.8 on 2025-11-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_examupload_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='examupload',
            name='processed_file',
            field=models.FileField(blank=True, help_text='The generated result file with ranks and analysis', null=True, upload_to='results/%Y/%m/%d/'),
        ),
    ]
