# backend/analytics/utils.py
import io
import zipfile
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors

def generate_student_reports(df, exam_title):
    """
    Generates a ZIP file containing individual PDF report cards for each student.
    Returns: BytesIO object (the zip file in memory)
    """
    zip_buffer = io.BytesIO()

    # Identify subject columns (same logic as analysis.py, roughly)
    # We assume the DF passed here is already cleaned and has 'Total', 'Rank', etc.
    exclude_cols = ['id', 'adm', 'name', 'student', 'phone', 'total', 'average', 'rank', 'mean', 'grade']
    subject_cols = [col for col in df.columns if col.lower() not in exclude_cols]

    # --- FIX IS HERE: Removed "false_compress=False" ---
    with zipfile.ZipFile(zip_buffer, 'a', zipfile.ZIP_DEFLATED) as zip_file:
        
        # Loop through every student in the dataframe
        for index, row in df.iterrows():
            
            # 1. Setup PDF Buffer
            pdf_buffer = io.BytesIO()
            p = canvas.Canvas(pdf_buffer, pagesize=A4)
            width, height = A4

            # 2. Draw Header
            p.setFont("Helvetica-Bold", 18)
            p.drawCentredString(width / 2, height - 50, "OFFICIAL REPORT CARD")
            
            p.setFont("Helvetica", 14)
            p.drawCentredString(width / 2, height - 75, exam_title)
            
            p.setLineWidth(1)
            p.line(50, height - 90, width - 50, height - 90)

            # 3. Draw Student Details
            # Try to find a name column, otherwise use index
            student_name = str(row.get('Name', row.get('name', f'Student {index+1}')))
            
            p.setFont("Helvetica-Bold", 12)
            p.drawString(50, height - 130, f"Name: {student_name}")
            p.drawString(50, height - 150, f"Position: {int(row.get('Rank', 0))}")
            p.drawString(300, height - 150, f"Total Score: {row.get('Total', 0)}")
            p.drawString(300, height - 130, f"Average: {row.get('Average', 0):.2f}")

            # 4. Draw Subjects Table (Manual Drawing)
            y_position = height - 200
            p.setFont("Helvetica-Bold", 12)
            p.drawString(50, y_position, "Subject")
            p.drawString(300, y_position, "Score")
            y_position -= 20
            p.line(50, y_position + 15, 400, y_position + 15)

            p.setFont("Helvetica", 12)
            for subject in subject_cols:
                score = row.get(subject, 0)
                p.drawString(50, y_position, str(subject).capitalize())
                p.drawString(300, y_position, str(score))
                y_position -= 20
            
            # 5. Footer
            p.setFont("Helvetica-Oblique", 10)
            p.drawCentredString(width / 2, 50, "Generated by School Exam Analyzer SaaS")

            # 6. Save PDF
            p.showPage()
            p.save()

            # 7. Add PDF to Zip
            pdf_buffer.seek(0)
            # Create a clean filename (remove weird characters)
            clean_name = "".join([c for c in student_name if c.isalpha() or c.isdigit() or c==' ']).strip()
            zip_file.writestr(f"{int(row.get('Rank', 0))}_{clean_name}.pdf", pdf_buffer.read())

    zip_buffer.seek(0)
    return zip_buffer